### ISSUE TITLE
Syntax highlighting and error notice

### ISSUE THREAD

**Issue by luisrieke** [SkyGuardian42/piko.space#1]
When I copy some code initially into the editor it looks like this:

<img width="490" alt="image" src="https://user-images.githubusercontent.com/66038170/204096475-b0d131ef-e9d2-4b8c-baa1-ce3bb4792079.png">

- error correction is shown within the code
- no highlighting

After a hard reload the editor looks perfekt ✨

<img width="490" alt="image" src="https://user-images.githubusercontent.com/66038170/204096552-8a0d4570-8190-4b77-b35d-3a46b7a6f9b7.png">

- no spelling error notice within code
- wonderful highlighting

After typing anything anywhere within the editor the error highlighting in the code gets activated again:

<img width="488" alt="image" src="https://user-images.githubusercontent.com/66038170/204096695-ac4b3dca-3d42-4919-a52f-50bbaa483be0.png">

If you have any questions to these comments ask your flat mate who loves your software 😘

**Comment by malte-j** [comment]
Should be fixed! Can you try hard-reloading once or twice, and tell me if it's working for you?
