### ISSUE TITLE
Feature resquest: h1 per "Slash" e.g. /h1

### ISSUE THREAD

**Issue by luisrieke** [SkyGuardian42/piko.space#10]
<img width="252" alt="image" src="https://user-images.githubusercontent.com/66038170/214888318-fbe49def-6c09-499e-a526-024ae019ebff.png">

As always, just an idea - but would be amazing to have a workflow like Notion / Wordpress / VIsual Studio Code etc. where you easily just type something and then press Enter to get a formatting.

If you have any questions ask your flat mate 😉

**Comment by malte-j** [comment]
You can use markdown for formatting, so typing "#" and then your title will create a title! But there needs to be some kind of hint for new users, so maybe adding a "/" menu should be done.
