### ISSUE TITLE
Feature request / boyscout: clickable area

### ISSUE THREAD

**Issue by luisrieke** [SkyGuardian42/piko.space#2]
Tiny feature wish - could you make the whole highlighted area clickable?

<img width="534" alt="image" src="https://user-images.githubusercontent.com/66038170/204350128-af9d1400-2b51-4c39-b712-6b96b7e74572.png">

Right now a big part is not clickable:

![image](https://user-images.githubusercontent.com/66038170/204351084-014cb4cd-6006-48f5-b314-c16523e16211.png)

Would be wonderful if it's like this:

![image](https://user-images.githubusercontent.com/66038170/204350748-a3b78340-361e-4692-8cd1-258570263ad6.png)

**Comment by malte-j** [comment]
Done!
