### ISSUE TITLE
Bug: changing title of file

### ISSUE THREAD

**Issue by luisrieke** [SkyGuardian42/piko.space#3]
![Nov-29-2022 11-05-33](https://user-images.githubusercontent.com/66038170/204500125-aedc3128-e62f-4851-8c0e-18016a7ecdfd.gif)

if I change the title of the file and I'm writing quick, it doesn't remember all the keys

if you have questions - not sure if it's clear what I wanna say - ask your flatmate 😘

**Comment by malte-j** [comment]
Fixed by debouncing the input, thanks!
