### ISSUE TITLE
Black Box between icons and title on mobile devices

### ISSUE THREAD

**Issue by luisrieke** [SkyGuardian42/piko.space#8]
When I access the search on mobile devices there's a little bug. Theres a black box which is not meant to be. Android, chrome, Samsung s10 lite in case you need this for Browser stack investigations.

**Comment by luisrieke** [comment]
![Screenshot_20221215-101117_Chrome](https://user-images.githubusercontent.com/66038170/207824225-ec3c8043-9598-4454-817d-6ac5ec128515.jpg)

**Comment by malte-j** [comment]
Some old version of the site is not compatible with the new way of encoding titles, a refesh should fix this.
